import {
  IconBook,
  IconBriefcase,
  IconBuilding,
  IconChartBar,
  IconCloud,
  IconCode,
  IconCoffee,
  IconCommand,
  IconCompass,
  IconCpu,
  IconDatabase,
  IconDeviceLaptop,
  IconFolder,
  IconGhost,
  IconHexagonFilled,
  IconPalette,
  IconPlanet,
  IconRocket,
  IconTerminal,
  IconTrophy,
  IconUsers,
} from "@tabler/icons-react";

export const WORKSPACE_ICONS = [
  { id: "hexagon", icon: IconHexagonFilled },
  { id: "briefcase", icon: IconBriefcase },
  { id: "folder", icon: IconFolder },
  { id: "building", icon: IconBuilding },
  { id: "users", icon: IconUsers },
  { id: "laptop", icon: IconDeviceLaptop },
  { id: "code", icon: IconCode },
  { id: "palette", icon: IconPalette },
  { id: "book", icon: IconBook },
  { id: "chart", icon: IconChartBar },
  { id: "cloud", icon: IconCloud },
  { id: "coffee", icon: IconCoffee },
  { id: "command", icon: IconCommand },
  { id: "compass", icon: IconCompass },
  { id: "cpu", icon: IconCpu },
  { id: "database", icon: IconDatabase },
  { id: "ghost", icon: IconGhost },
  { id: "planet", icon: IconPlanet },
  { id: "rocket", icon: IconRocket },
  { id: "terminal", icon: IconTerminal },
  { id: "trophy", icon: IconTrophy },
];
